- name: install Javascript
  hosts: nodes
  tasks:
  - name: ensure javascript is installed
    apt:
      name: javascript
      state: latest
  - name: install docker
    apt:
      name: docker.io
      state: latest